{"ast":null,"code":"\n\n'use strict';\n\nvar logError = function logError() {\n  for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {\n    args[_key] = arguments[_key];\n  }\n  if (args.length === 1 && args[0] instanceof Error) {\n    var err = args[0];\n    console.error('Error: \"' + err.message + '\".  Stack:\\n' + err.stack);\n  } else {\n    console.error.apply(console, args);\n  }\n};\nmodule.exports = logError;","map":{"version":3,"names":["logError","args","length","Error","err","console","error","message","stack","apply","module","exports"],"sources":["/Users/hez/code/boatApp/node_modules/react-native/Libraries/Utilities/logError.js"],"sourcesContent":["/**\n * Copyright (c) Meta Platforms, Inc. and affiliates.\n *\n * This source code is licensed under the MIT license found in the\n * LICENSE file in the root directory of this source tree.\n *\n * @format\n * @flow strict\n */\n\n'use strict';\n\n/**\n * Small utility that can be used as an error handler. You cannot just pass\n * `console.error` as a failure callback - it's not properly bound.  If passes an\n * `Error` object, it will print the message and stack.\n */\nconst logError = function (...args: $ReadOnlyArray<mixed>) {\n  if (args.length === 1 && args[0] instanceof Error) {\n    const err = args[0];\n    console.error('Error: \"' + err.message + '\".  Stack:\\n' + err.stack);\n  } else {\n    console.error.apply(console, args);\n  }\n};\n\nmodule.exports = logError;\n"],"mappings":";;AAUA,YAAY;;AAOZ,IAAMA,QAAQ,GAAG,SAAXA,QAAQ,GAA6C;EAAA,kCAA7BC,IAAI;IAAJA,IAAI;EAAA;EAChC,IAAIA,IAAI,CAACC,MAAM,KAAK,CAAC,IAAID,IAAI,CAAC,CAAC,CAAC,YAAYE,KAAK,EAAE;IACjD,IAAMC,GAAG,GAAGH,IAAI,CAAC,CAAC,CAAC;IACnBI,OAAO,CAACC,KAAK,CAAC,UAAU,GAAGF,GAAG,CAACG,OAAO,GAAG,cAAc,GAAGH,GAAG,CAACI,KAAK,CAAC;EACtE,CAAC,MAAM;IACLH,OAAO,CAACC,KAAK,CAACG,KAAK,CAACJ,OAAO,EAAEJ,IAAI,CAAC;EACpC;AACF,CAAC;AAEDS,MAAM,CAACC,OAAO,GAAGX,QAAQ"},"metadata":{},"sourceType":"script"}